# Site settings
title: End-To-End AI
description: > # this means to ignore newlines until "baseurl:"
  We seek to provide high quality information on different aspects of Artificial
  Intelligence, including Machine Learning, Deep Learning, Reinforcement
  Learning, and Computer Vision.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.endtoend.ai" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: true
# disqus_shortname: 'www.endtoend.ai'

# Build settings
markdown: kramdown

# Put all pages except index.md in _pages directory
include:
 - "_pages"

front_page_order:
#  - "RL Environments"
 - "Atari Environments"
 - "Sutton and Barto Notebooks"
 - "Slides"
 - "Blog"
 - "AI for Prosthetics"

plugins:
 - jekyll-redirect-from
