# Site settings
title: End-To-End AI
description: > # this means to ignore newlines until "baseurl:"
  We seek to provide high quality information on different aspects of Artificial
  Intelligence, including Machine Learning, Deep Learning, Reinforcement
  Learning, and Computer Vision.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.endtoend.ai" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: true
# disqus_shortname: 'www.endtoend.ai'

# Build settings
markdown: kramdown

# Put all pages except index.md in _pages directory
include:
 - "_pages"

front_page_order:
#  - "RL Environments"
 - "AI for Prosthetics"
 - "Atari Environments"
 - "MuJoCo Environments"
 - "CTRL: Current Topics in RL"
# - "Demystifying Experience Replay"
 - "DQN Book"
# - "Policy Gradient Book"
#  - "Practical Reinforcement Learning"
 - "Sutton and Barto Notebooks"
 - "Slides"
 - "Blog"

front_page_links:
 - name: "DQN Book"
   url: "https://www.dqnbook.org/"
   image: "/assets/home/dqn.png"
   image_type: cover
   description: >
       Read the early draft of the Deep Q-Networks (DQN) book. This book
       explores various improvements of DQN that achieved superhuman results.
 - name: "Policy Gradient Book"
   url: "https://www.policygradientbook.org/"
   image: "/assets/home/pg.png"
   image_type: contain
   description: >
       Read the early draft of the Policy Gradient book. Policy gradient methods
       are used in various state-of-the-art reinforcement learning applications.
plugins:
 - jekyll-redirect-from
