# basic options
title: End to End AI

author1: Seungmin Brian Lee
email1: sl3254@columbia.edu
author1-description: Computer Vision.
author1-github_username:  briansmlee
author1-linkedin_username: seungminbrianlee

author2: Seung Jae Ryan Lee
email2: seungjl@princeton.edu
author2-description: Reinforcement Learning.
author2-github_username:  seungjaeryanlee
author2-linkedin_username: seungjaeryanlee

# Build settings
markdown: kramdown
theme: minima

permalink: pretty

plugins:
  - jekyll-feed
