# Site settings
title: endtoendAI
description: > # this means to ignore newlines until "baseurl:"
  We seek to provide high quality information on different aspects of Artificial
  Intelligence, including Machine Learning, Deep Learning, Reinforcement
  Learning, and Computer Vision.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.endtoend.ai" # the base hostname & protocol for your site

twitter_username: seungjaeryanlee
github_username:  jekyll

title_image: /favicon.png

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: true
# disqus_shortname: 'www.endtoend.ai'

# Build settings
markdown: kramdown

# Put all pages except index.md in _pages directory
include:
 - "_pages"

plugins:
 - jekyll-redirect-from

featured_page:
  # link: /deep-rl-seminar/2
  # title: "Deep RL Seminar: Week 2"
  # supporting_text: "This week, we reviewed various improvements made to the Deep Q-Network algorithm."
  # image_url: /assets/blog/deep-rl-seminar/2/rainbow.png
  # cover_or_contain: contain
  link: /rl-weekly/12
  title: "RL Weekly Week 12"
  supporting_text: "This week, we look at a new demo dataset of Atari games that include trajectories and human gaze. We also look at PEARL, a new meta-RL method that boasts sample efficiency and performance superior to previous state-of-the-art algorithms. Finally, we look at a novel method of incorporating intrinsic rewards."
  image_url: /assets/blog/rl-weekly/12/16_games.png
  cover_or_contain: contain

front_page_links:
  - name: "RL Weekly"
    url: "/tags/rl-weekly/"
    image: "/assets/home/rl-weekly.png"
    image_type: contain
    description: >
      Get the highlights of reinforcement learning in both research and industry
      every week.
  # - name: "CTRL: Current Topics in RL"
  #   url: "/ctrl/"
  #   image: "/assets/home/ctrl.png"
  #   image_type: contain
  #   description: >
  #     Read summaries of new papers in Reinforcement Learning, ranging from
  #     theoretical studies to experiments.
  - name: "Slow Papers"
    url: "/tags/slowpapers/"
    image: "/assets/home/microscope.png"
    image_type: contain
    description: >
      Read extended explanations of seminal papers.
  - name: "Fast Papers"
    url: "/tags/fastpapers/"
    image: "/assets/home/ctrl.png"
    image_type: contain
    description: >
      Read summaries of key ideas from a wide variety of papers.
  # - name: Resources
  #   url: "/resources"
  #   image: "/assets/home/resources.png"
  #   image_type: contain
  #   description: >
  #     Presentation slides, snipplets of code, and other useful resources for
  #     studying reinforcement learning.
  - name: "Blog"
    url: "/blog/"
    image: "/assets/home/blog.png"
    image_type: contain
    description: >
      We blog about our AI-related experience, including internships, 
      competitions, and research.
  # - name: "AI for Prosthetics"
  #   url: "/ai-for-prosthetics/"
  #   image: "/assets/_pages/ai-for-prosthetics/card.jpg"
  #   image_type: cover
  #   description: >
  #     This is a guide for the NIPS 2018 AI for Prosthetics challenge with a 
  #     helper package and a series of blog posts.
  # - name: "Atari Environments"
  #   url: "/envs/gym/atari/"
  #   image: "/assets/home/atari.jpeg"
  #   image_type: cover
  #   description: >
  #     Read about state-of-the-art results for each environment of Atari 2600,
  #     the standard suite for analyzing performance of various Reinforcement
  #     Learning methods.
  # - name: "MuJoCo Environments"
  #   url: "/envs/gym/mujoco/"
  #   image: "/assets/home/mujoco.png"
  #   image_type: cover
  #   description: >
  #     Read about continuous control environments created with MuJoCo, a
  #     proprietary physics engine for detailed, efficient rigid body simulations
  #     with contacts.
  # - name: "Sutton and Barto Notebooks"
  #   url: "/sutton-barto-notebooks/"
  #   image: "/assets/home/sutton-barto.png"
  #   image_type: contain
  #   description: >
  #     This repository contains Jupyter Notebook of implementations of insightful
  #     figures in Sutton and Barto's <i>Reinforcement Learning: An Introduction
  #     </i>.
  # - name: "Slides"
  #   url: "/slides/"
  #   image: "/assets/home/slides.png"
  #   image_type: contain
  #   description: >
  #     This is a collection of presentation slides summarizing contents of books
  #     and state-of-the-art results.
  # - name: "DQN Book"
  #   url: "https://www.dqnbook.org/"
  #   image: "/assets/home/dqn.png"
  #   image_type: cover
  #   description: >
  #     Read the early draft of the Deep Q-Networks (DQN) book. This book
  #     explores various improvements of DQN that achieved superhuman results.
  # - name: "Policy Gradient Book"
  #   url: "https://www.policygradientbook.org/"
  #   image: "/assets/home/pg.png"
  #   image_type: contain
  #   description: >
  #     Read the early draft of the Policy Gradient book. Policy gradient methods
  #     are used in various state-of-the-art reinforcement learning applications.
