# basic options
title: End to End AI
description: Brian and Ryan's Blog

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# Header settings
header_title: End to End AI
header_description: End to End AI

permalink: /:categories/:title

plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Fixed Mixed Content Error
url: "https://www.endtoend.ai"

# Put all pages except index.md in _pages directory
include:
  - "_pages"
  - "_pages/mooc"
  - "_pages/mooc/aind"
  - "_pages/mooc/dlnd"
  - "_pages/tour"
  - "_pages/tour/ai"
  - "_pages/tour/ml"
  - "_pages/tour/dl"
  - "_pages/tour/rl"
  - "_posts"
