# Site
name: "endtoend.ai"
title: "endtoend.ai"
description: "Studying Artificial Intelligence, from backbone to application."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
# baseurl: /
google_analytics: 'UA-117425613-1'
disqus: 'www-endtoend-ai'
# newsletter: 'https://www.getrevue.co/profile/seungjaeryanlee'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ryan:
    name: Seungjae Ryan Lee
    display_name: Ryan
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: seungjaeryanlee@gmail.com
    web: https://www.seungjaeryanlee.com
    twitter: https://twitter.com/seungjaeryanlee
    description: "TODO."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [LICENSE.txt, Gemfile, Gemfile.lock]
